status = [
  # Buildkite: impure builds
  "buildkite/offchain-metadata-tools",
  # Hydra: build for required jobset
  "ci/hydra:Cardano:offchain-metadata-tools:required",
]
timeout_sec = 3600
required_approvals = 1
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
